language: node_js

node_js:
  - v8

notifications:
  slack:
    rooms:
      secure: qUOObzw7iyWo/jALEDDvrPQXeTiq8XU3us2F1gmeBXglGQJhoAhdmNvoQeDN4b1VIZ9hMcaF8drHJqTSgSfWmvWZxTwFYGOMPRNziw+v8Ca9TfXz9y1J1U1BNXHQ1PD7YaMEyXD0Vo8EmuCmHUA48aL1Nk+fOxoi7jIrXMwf55o6F/DIreVx6Wm1jRA5DjvOkifrayUVaIrYH/hKampKJfV5a+36mm4x/F2U5Q8D7zdkPcDV3X/TwkF7jNz7FqYQp4Ae+C5HkopJduFna8rfvvkFCRyBbhisqHcOokyQ4grlwtl0hTdw3SOwNKu6dA7H+kop2W4bvNCcVQWZhJeScS7/EZbr1f5SGb8C6IEDvjZau/+JejR/x1B8zTZlDPcsaC6JEoFd5jMapWLGVYBMihcrEtVFjWNqJL/c7W2wr56x+puYAZCFN3E2RsR04+NRgUfQXqntk5GGq7I+RRd1uQyuDmYT1TfBq/ifOctKH/6oc2aUcaYfCWhEVWWhRfnxoFfAaQrHWSUxkSY4PWlYorGH9IiuWtgk5pW0qDAVQ7tEhgcxvFLn+6AbFRQ7Oztx0epDWRN7/I+5Xln11KAgswGx+BIXkzqJP4lFhN5D1c0P6NC45TbI37OF5vglJs/5Kr3lSVdtAESwF1nSbxnlSCp4VYn4Zps1KCukLPWpeJU=